//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horarios
    {
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> NumeroSala { get; set; }
        public string Titulo { get; set; }
        public string id_acomodador { get; set; }
        public string id_horario { get; set; }
    
        public virtual Acomodador Acomodador { get; set; }
        public virtual Peliculas Peliculas { get; set; }
        public virtual Salas Salas { get; set; }
    }
}
